x-common-config: &common-config
  build:
    context: .
    dockerfile: Dockerfile
  user: "1000:1000"
  init: true
  cap_drop:
    - ALL
  security_opt:
    - no-new-privileges:true
  volumes:
    - ~/nanobot_workspace:/home/nanobot/.nanobot
    - ~/nanobot_workspace/media:/home/nanobot/.nanobot/workspace/media
    - ~/nanobot_workspace/history:/home/nanobot/.nanobot/workspace/history

services:
  nanobot-gateway:
    container_name: nanobot-gateway
    <<: *common-config
    command: ["gateway"]
    restart: unless-stopped
    ports:
      - 18790:18790

  nanobot-cli:
    <<: *common-config
    profiles:
      - cli
    command: ["status"]
    stdin_open: true
    tty: true
