x-common-config: &common-config
  build:
    context: .
    dockerfile: Dockerfile.hardened
  user: "1000:1000"
  init: true
  read_only: true
  tmpfs:
    - /tmp
  volumes:
    - ~/nanobot_workspace:/home/nanobot/.nanobot
  cap_drop:
    - ALL
  security_opt:
    - no-new-privileges:true
services:
  nanobot-gateway:
    container_name: nanobot-gateway-hardened
    <<: *common-config
    command: ["gateway"]
    restart: unless-stopped
    ports:
      - 18790:18790
    deploy:
      resources:
        limits:
          cpus: "8"
          memory: 28G
        reservations:
          cpus: "1"
          memory: 1G

  nanobot-api:
    container_name: nanobot-api-hardened
    <<: *common-config
    command:
      ["serve", "--host", "0.0.0.0", "-w", "/home/nanobot/.nanobot/api-workspace"]
    restart: unless-stopped
    ports:
      - 127.0.0.1:8900:8900
    deploy:
      resources:
        limits:
          cpus: "8"
          memory: 28G
        reservations:
          cpus: "1"
          memory: 1G

  nanobot-cli:
    <<: *common-config
    profiles:
      - cli
    command: ["status"]
    stdin_open: true
    tty: true
